### ISSUE TITLE
Power cycles on after turning off using button or remote

### ISSUE THREAD

**Issue by Hootanic** [PiboxyTeam/remoteswitch#2]
When using the IR remote or power button to power off the device, the device will safely shutdown and remain off for several minutes, then power on again without initiating a power on from remote or button. Using ssh to sudo shutdown keeps it off, as does disconnecting power supply between the power off/on cycle.

**Comment by PiBoxY** [comment]
Wait a few minutes after shutdown, and then automatically boot up, can it be turned off by button or remote control?

**Comment by Hootanic** [comment]
After doing some prolonged testing, I'm thinking that the HDMI cable is generating enough current that it starts a boot sequence. The device will shutdown from both button and remote and stay off until on my tv menu I use the menu options to pull up the input selection menu to switch back to TV. When I switch to another input and then shut it down, it will stay off. I will test with some different HDMI cables and record my results.

**Comment by Hootanic** [comment]
After doing more testing, it is not the hdmi cable, the issue is in fact my LG tv remote is triggering the IR feature of the piboxy. Using the up/down buttons for my remote triggers the same on/off single button command as the included IR control, apparently.

**Comment by PiBoxY** [comment]
This is an inherent problem with **infrared** remote control and we will collect a **compatible list**  monitors / peripherals as soon as possible, thanks for your support.If you have more questions about the product itself (replacement / return), please contact **sales@piboxy.com**
